### ISSUE TITLE
File zshow_gwmon_log.prog.xml contains program code, not metadata

### ISSUE THREAD

**Issue by chrisaasan** [SAP-samples/security-services-tools#13]
It looks like the file zshow_gwmon_log.prog.xml contains the program itself, and not metadata.

**Comment by larshp** [comment]
ref https://github.com/SAP-samples/security-services-tools/blob/main/ABAP/basis/zshow_gwmon_log.prog.xml

**Comment by FrankBuchholz** [comment]
Oh, in SE38 I had downloaded the code into the wrong file. 
Solved with https://github.com/SAP-samples/security-services-tools/commit/29ab046c6a2c510f78f148fa6bb369f48d8f99d3
Thank you for pointing this out!
