### ISSUE TITLE
ZSPFRECOMMENDED - parameter rdisp/gui_auto_logout

### ISSUE THREAD

**Issue by diegoy84** [SAP-samples/security-services-tools#15]
just a small observation...

parameter rdisp/gui_auto_logout is as per default 3600 (in seconds). the program tries to match to 1H (actually the same thing) and marks it as not aligned with the recommendations. 
Considering the default value (i.e in S4HANA 2020) is 3600 I'd put it that way to avoid changing the default kernel value to match the rule. Reviewed note 2926224 and it's set to 1H in the spreadsheet but I've always seen that parameter expressed in seconds.

**Comment by FrankBuchholz** [comment]
Hi diegoy84,

thank you for pointing this out!
I've changed the check in report ZSPFRECOMMENDED for this parameter rdisp/gui_auto_logout from 1H to 3600 via https://github.com/SAP-samples/security-services-tools/commit/5880c7ff520715fdb702ec9946f500210b3c4965
In addition I added another popup for showing the data enabling copy&paste for long values.

Greetings
Frank
