### ISSUE TITLE
ZSYSREC_NOTELIST_72_SP08 Field "AGSSN_SYSREC_MAX_RFC_TIME" is unknown

### ISSUE THREAD

**Issue by RaBa1** [SAP-samples/security-services-tools#16]
missing constant? 
constants  agssn_sysrec_max_rfc_time   type dnot_field value 'SYSREC_MAX_RFC_TIME'.   " RaBa1 Field unknown

Field "AGSSN_SYSREC_MAX_RFC_TIME" is unknown. It is neither in one of
the specified tables nor defined by a "DATA" statement. "DATA" statement.

**Comment by FrankBuchholz** [comment]
Hi RaBa1,
thank you for pointing this out. In February 2023 I did some small changes but missed to test it on various support package levels. 
The bug is solved now with https://github.com/SAP-samples/security-services-tools/commit/10d7bcccdba123ee7686b2a10c1c24f46fccbc59 
Greetings,
Frank
