### ISSUE TITLE
Update Error: No character set conversions possible for one or more characters

### ISSUE THREAD

**Issue by abap-weasel** [SAP-samples/security-services-tools#21]
Hi guys,

when trying to pull security-services-reports I get errors like this for each report:

No character set conversions possible for one or more characters. Section from the source buffer from the first character that could not be converted: "A7 27 2E 20 20 20 20 67 73 5F 72 65 73 75 6C 74
No character set conversions possible for one or more characters. Section from the source buffer from the first character that could not be converted: "A7 27 2E 20 20 20 20 67 73 5F 72 65 73 75 6C 74 (.'. gs_result)".
Import of object ZRFC_STATRECS_SUMMARY failed

We are using latest abapgit 1.125.0 (updated earlier today). Issue is exlusive to this repository as all other repos we imported to our system could be updated without errors.

Currently we have version from 04/2023 active in system, so back then it worked.

**Comment by FrankBuchholz** [comment]
I had updated ZRFC_STATRECS_SUMMARY two month ago.

It could be related to some Unicode conversion issue, but in fact, I've no idea yet how this could happen...

**Comment by daberlin** [comment]
Same for me:

```
Character set conversion not possible for one or more characters. Source data from the first non-convertible byte: "C4 27 2E 0A 20 20 20 20 20 20 20 20 20 20 52 45 (.'.. RE)".
Import of object ZCHECK_NOTE_2934135 failed
```

```
Character set conversion not possible for one or more characters. Source data from the first non-convertible byte: "A7 27 2E 20 20 20 20 67 73 5F 72 65 73 75 6C 74 (.'. gs_result)".
Import of object ZRFC_STATRECS_SUMMARY failed
```

**Comment by daberlin** [comment]
For ZRFC_STATRECS_SUMMARY, the problem seems to be this line: 
`    WHEN '§'.    gs_result-tasktype = 'lrrfc'. "(417) paragraph sign`

It triggers an exception in ABAPGIT, line 28.076, METHOD CONVERT

**Comment by FrankBuchholz** [comment]
That means that ABAPGIT cannot handle the paragraph sign in a string constant - at least not in this encoding. 

(Copy and paste or upload of the code into SE38 work fine.) 

I'll try to search for a replacement.. and if I do not find any, I'll just deactivate this line, which is not too important.

**Comment by FrankBuchholz** [comment]
Please try again
